#!/usr/bin/env bash

__root__=$(dirname $(dirname ${BASH_SOURCE[0]}))
__export__() { export BCH_KRON_${1}="${2}" ; }

__export__  _root  ${__root__}
__export__  _bin   ${__root__}/.bch.bin
__export__  _lbin  ${__root__}/.bch.lbin
__export__  _init  ${__root__}/.bch.init/init.sh

:::linkall::: ${__root__}/.bch.lbin
:::append::: ${__root__}/.bch.bin

source ${__root__}/.bch.init/init.sh

__export__ d_CROND   ~/.tmp.bch.kron
__export__ f_SERVING ~/.tmp.bch.kron/serving
__export__ f_ANSWERED ~/.tmp.bch.kron/answered

unset __root__
unset __export__
